komarovalexander/ka-table

- README.md
- package.json
- src/Demos/SearchDemo/SearchDemo.tsx
- src/lib/Components/NoDataRow/NoDataRow.test.tsx
- src/lib/Components/NoDataRow/NoDataRow.tsx
- src/lib/Components/Rows/Rows.test.tsx
- src/lib/Components/Rows/Rows.tsx
- src/lib/Components/Table/Table.tsx
- src/lib/Components/TableBody/TableBody.test.tsx
- src/lib/Components/TableBody/TableBody.tsx
- src/lib/Models/VirtualScrolling.ts
- src/lib/Utils/Virtualize.test.ts
- src/lib/style.scss
- src/lib/types.ts
#17 
```
const tableOption: ITableOption = {
//...
noDataRow: () => 'No Data Found',
//...
};
```
> Add ability to show custom message in case of no data in the table

- README.md
- gulpfile.js
- package.json
- public/static/icons/ManyColumnsDemo.svg
- src/Demos/Demos.tsx
- src/Demos/ManyColumnsDemo/ManyColumnsDemo.test.tsx
- src/Demos/ManyColumnsDemo/ManyColumnsDemo.tsx
- src/lib/Components/Table/Table.tsx
- src/lib/Components/TableBody/TableBody.test.tsx
- src/lib/Components/TableBody/TableBody.tsx
- src/lib/Utils/ActionUtils.test.ts
- src/lib/Utils/ActionUtils.ts
- src/lib/style.scss
#29
Horizontal scroll bar works with header and body
https://komarovalexander.github.io/ka-table/#/many-columns
> Add horizontal scroll bar in case of many columns

- package.json
- src/lib/Utils/Virtualize.ts
- src/lib/Utils/__snapshots__/Virtualize.test.ts.snap
> Fix scrolling flickers when using virtual scrolling

- package.json
- src/Demos/RemoteDataDemo/RemoteDataDemo.tsx
- src/Demos/RemoteDataDemo/serverEmulator.ts
- src/lib/Components/Paging/Paging.tsx
- src/lib/Reducers/kaReducer.ts
- src/lib/Utils/PagingUtils.test.ts
- src/lib/Utils/PagingUtils.ts
- src/lib/actionCreators.ts
- src/lib/enums.ts
pagesCount sets the count of pages for specific data and disables local data pagination:
```
paging: {
pagesCount?: number; 
// ....
}
```
also the action creator to update pagesCount value was added:
```
updatePagesCount(pagesCount: number)
```
> Add paging.pagesCount option

- package.json
- src/lib/Components/DetailsRow/DetailsRow.test.tsx
- src/lib/Components/DetailsRow/DetailsRow.tsx
> Add colSpan to details row

- package.json
- src/index.tsx
- src/lib/Reducers/kaReducer.ts
> Fix type issue in kaReducer.ts on line 77

- README.md
- package.json
- src/Demos/BootstrapDemo/BootstrapDemo.scss
- src/Demos/BootstrapDemo/BootstrapDemo.tsx
- src/lib/Components/Paging/Paging.test.tsx
- src/lib/Components/Paging/Paging.tsx
- src/lib/Components/PagingIndex/PagingIndex.test.tsx
- src/lib/Components/PagingIndex/PagingIndex.tsx
- src/lib/Components/PagingPages/PagingPages.test.tsx
- src/lib/Components/PagingPages/PagingPages.tsx
- src/lib/Components/Table/Table.tsx
- src/lib/Models/ChildComponents.ts
- src/lib/Models/CssClasses.ts
- src/lib/Utils/PropsUtils.test.ts
- src/lib/Utils/PropsUtils.ts
- src/lib/props.ts
>  Add pagingIndex & pagingPages child components

- package.json
- src/lib/Components/TableBody/TableBody.tsx
- src/lib/Models/ChildComponents.ts
- src/lib/types.ts
table body can be customized in childComponents
> Add 'ref' support to all properties of childComponents, and childComponents.tableBody 

- package.json
- src/Demos/MaterialDemo/MaterialDemo.tsx
- src/lib/Components/FilterCell/FilterCell.tsx
- src/lib/Utils/DomUtils.test.ts
- src/lib/Utils/DomUtils.ts
>  Fix header overlapping issue

- package.json
- public/data/employees.json
- src/Demos/DemoText.tsx
- src/Demos/Demos.tsx
- src/Demos/JsonDemo/JsonDemo.test.tsx
- src/Demos/JsonDemo/JsonDemo.tsx
- src/lib/Components/FilterCell/FilterCell.tsx
- src/lib/Components/FilterRow/FilterRow.tsx
- src/lib/Utils/CellResizeUtils.test.ts
- src/lib/Utils/DomUtils.test.ts
- src/lib/Utils/DomUtils.ts
> Fix filter row empty cell scrolling

- package.json
- public/index.html
- src/Demos/CustomThemeDemo/CustomThemeDemo.scss
- src/Demos/Demos.scss
- src/Demos/Demos.tsx
- src/Demos/KeyboardNavigationDemo/KeyboardNavigation.scss
- src/Demos/KeyboardNavigationDemo/KeyboardNavigationDemo.tsx
- src/lib/Components/HeadCellResize/HeadCellResize.test.tsx
- src/lib/Components/HeadCellResize/HeadCellResize.tsx
- src/lib/Utils/PropsUtils.test.ts
- src/lib/Utils/PropsUtils.ts
#115 - resizing 
#114 - multiple Selection
> Fix resizing and reordering bug & multiple selection bug

- package.json
- src/lib/Components/HeadCell/HeadCell.tsx
- src/lib/Components/HeadRow/HeadRow.tsx
- src/lib/Components/TableHead/TableHead.tsx
- src/lib/Components/TableWrapper/TableWrapper.tsx
- src/lib/Utils/ComponentUtils.test.ts
> Don't spread parent properties in case they have different type

- package.json
- src/lib/Components/TableBody/TableBody.test.tsx
- src/lib/Components/TableBody/TableBody.tsx
Allow style customization for tbody element
> Allow style customization for tbody element

- package.json
- src/Demos/ColumnResizingDemo/ColumnResizingDemo.tsx
- src/lib/Components/Table/Table.tsx
> Fix rootDivContent override

- package.json
- src/Demos/BootstrapDemo/BootstrapDemo.scss
- src/Demos/CustomPagingDemo/CustomPagingDemo.tsx
- src/Demos/Demos.tsx
- src/Demos/ManyRowsDynamicDemo/ManyRowsDynamicDemo.test.tsx
- src/Demos/ManyRowsDynamicDemo/ManyRowsDynamicDemo.tsx
- src/Demos/MaterialDemo/MaterialDemo.scss
- src/Demos/MenuItems.tsx
- src/Demos/PagingDemo/PagingDemo.tsx
- src/lib/Components/DataRow/DataRow.test.tsx
- src/lib/Components/DataRow/DataRow.tsx
And add demo for virtual scrolling of dynamic size items #50
> Fix dataRow.ref overriding

- package.json
- src/Demos/ManyRowsDynamicDemo/ManyRowsDynamicDemo.tsx
- src/lib/Components/TableWrapper/TableWrapper.tsx
- src/lib/Reducers/kaReducer.test.ts
- src/lib/Reducers/kaReducer.ts
- src/lib/Utils/Virtualize.test.ts
- src/lib/Utils/Virtualize.ts
> Fix ScrollTable in kaReducer if virtualScrolling is undefined

- .gitignore
- package.json
- src/lib/Components/Rows/Rows.test.tsx
- src/lib/Components/Rows/Rows.tsx
- src/lib/props.ts
> Fix group text formatting

- README.md
- gulpfile.js
- package.json
> Add peerDependencies to package.json

- package.json
- src/lib/Utils/PropsUtils.test.ts
- src/lib/Utils/PropsUtils.ts
> Update pagination during group expansion/contraction

- package.json
- src/lib/Components/Loading/Loading.tsx
- src/lib/Components/Table/Table.tsx
- src/lib/Models/ChildComponents.ts
- src/lib/props.ts
```
childComponents={{
loading: {
content: ({ text }) => (
<>
<div className='ka-loading-text'>{text}</div>
</>
)
}
}}
```
> Loading panel customization

- package.json
- src/Demos/SortingDemo/SortingDemo.tsx
- src/lib/Components/HeadCellContent/HeadCellContent.tsx
- src/lib/Components/SortIcon/SortIcon.test.tsx
- src/lib/Components/SortIcon/SortIcon.tsx
- src/lib/Models/ChildComponents.ts
- src/lib/Models/Column.ts
- src/lib/Models/CssClasses.ts
- src/lib/Utils/SortUtils.test.ts
- src/lib/Utils/SortUtils.ts
- src/lib/props.ts
`column.isSortable` - disable sorting for specific column
`childComponents.sortIcon` - gives ability to customize sortIcon component
```
columns: [{
...
isSortable: false,
...
}],
childComponents={{
sortIcon: {
...
}
}}
```
Demo: https://komarovalexander.github.io/ka-table/#/sorting
Docs: http://ka-table.com/docs_props.html#toc1
> Add column.isSortable & childComponents.sortIcon

- package.json
- src/lib/Components/TableBodyContent/TableBodyContent.tsx
- src/lib/Components/VirtualizedRows/VirtualizedRows.tsx
- src/lib/Utils/CellUtils.ts
- src/lib/Utils/Virtualize.test.ts
- src/lib/Utils/Virtualize.ts
- src/lib/Utils/__snapshots__/Virtualize.test.ts.snap
> Fix - Virtual scrolling breaks when showing new row #242

- package.json
- src/lib/Components/HeadCellContent/HeadCellContent.tsx
> Fix useLayoutEffect warnings 

- .vscode/settings.json
- README.md
- package.json
- src/lib/Components/CellEditorState/CellEditorState.tsx
- src/lib/Components/NewRow/NewRow.tsx
- src/lib/Utils/CellUtils.test.ts
- src/lib/Utils/CellUtils.ts
- src/lib/Utils/ColumnUtils.test.ts
- src/lib/Utils/ColumnUtils.ts
- src/lib/Utils/DataUtils.ts
> Add rowData to newRow validation

- package.json
- src/lib/Components/CellEditorDate/CellEditorDate.test.tsx
- src/lib/Components/CellEditorDate/CellEditorDate.tsx
> Fix timezone issue on default date editor

- package.json
- src/Demos/DetailsRowDemo/DetailsRowDemo.tsx
- src/lib/Components/DetailsRow/DetailsRow.tsx
- src/lib/Models/ChildComponents.ts
- src/lib/Models/CssClasses.ts
#281 
```
childComponents: {
detailsCell: {
elementAttributes: () => ({
colSpan: 1
}),
}
}
```
> Add childComponents.detailsCell options

- package.json
- src/lib/Components/NoDataRow/NoDataRow.test.tsx
- src/lib/Components/NoDataRow/NoDataRow.tsx
- src/lib/Models/ChildComponents.ts
#281
```
childComponents: {
noDataCell: {
elementAttributes: () => ({
colSpan: 1
}),
}
}
```
> Add noDataCell childComponent

- package.json
- src/Demos/SearchDemo/SearchDemo.tsx
- src/lib/Components/NoDataRow/NoDataRow.tsx
- src/lib/Components/Table/Table.tsx
- src/lib/Components/TableWrapper/TableWrapper.test.tsx
- src/lib/Components/TableWrapper/TableWrapper.tsx
- src/lib/Utils/SortUtils.ts
- src/lib/props.ts
- src/lib/types.ts
```
noData={{
text: 'No Data Found',
hideHeader: boolean, // hide table header in case of no data
}}
```
> Add noData setting

- package.json
- src/lib/Utils/CellUtils.ts
> Fix header filter box floats out of view on Virtualized tables 

- package.json
- src/lib/Models/FilterOperator.ts
- src/lib/Utils/FilterUtils.ts
- src/lib/types.ts
new **rowData** parameter added to give user access to rowData in that function
```
filter={(props) => {
if (props.column.key === 'column1') {
return (value: number[], filterRowValue: number, rowData: any[]) =>  //... ;
}
}}
```
> Add rowData to filter function

- package.json
- src/Demos/ManyRowsDemo/ManyRowsDemo.tsx
- src/Demos/RemoteDataEditingDemo/RemoteDataEditingDemo.tsx
- src/lib/Components/CellEditor/CellEditor.tsx
- src/lib/Components/TableUncontrolled/TableUncontrolled.tsx
- src/lib/Components/TableUncontrolled/utils.test.ts
- src/lib/Components/TableUncontrolled/utils.ts
- src/lib/Components/VirtualizedRows/VirtualizedRows.tsx
- src/lib/Models/VirtualScrolling.ts
- src/lib/Utils/Virtualize.test.ts
- src/lib/Utils/Virtualize.ts
- src/lib/Utils/__snapshots__/Virtualize.test.ts.snap
> Add ability to show additional rows at top & bottom for virtualScrolling

- package.json
- src/lib/Components/Rows/Rows.tsx
- src/lib/Utils/GroupUtils.ts
- src/lib/Utils/__snapshots__/GroupUtils.test.ts.snap
- src/lib/Utils/__snapshots__/PropsUtils.test.ts.snap
- src/lib/props.ts
https://github.com/komarovalexander/ka-table/issues/349
> Add groupItems and columns to the GroupRow for better customization

- package.json
- src/Demos/HeaderFilterDemo/HeaderFilterDemo.tsx
- src/lib/Components/CellText/CellText.tsx
- src/lib/Components/PopupContent/PopupContent.tsx
- src/lib/Components/Rows/Rows.tsx
- src/lib/Utils/FilterUtils.ts
- src/lib/Utils/GroupUtils.test.ts
- src/lib/Utils/GroupUtils.ts
- src/lib/types.ts
> Add rowData as a parameter to a format function

- .eslintrc.js
- src/Demos/Demos.tsx
- src/Demos/FilterRowCustomLogicDemo/FilterRowCustomLogicDemo.tsx
- src/Demos/HeaderFilterLogicDemo/HeaderFilterLogicDemo.test.tsx
- src/Demos/HeaderFilterLogicDemo/HeaderFilterLogicDemo.tsx
- src/Demos/MenuItems.tsx
- src/lib/Components/PopupContent/PopupContent.tsx
- src/lib/Components/PopupContentItem/PopupContentItem.tsx
- src/lib/Components/PopupContentItemText/PopupContentItemText.test.tsx
- src/lib/Components/PopupContentItemText/PopupContentItemText.tsx
- src/lib/Models/ChildComponents.ts
- src/lib/Models/Column.ts
- src/lib/Utils/FilterUtils.test.ts
- src/lib/Utils/FilterUtils.ts
- src/lib/Utils/__snapshots__/FilterUtils.test.ts.snap
1. column.headerFilterListItems 
2. childComponents.popupContentItemText
3. column.filter
> Filtering improvements

- package.json
- src/lib/Utils/CellUtils.ts
- src/lib/utils.ts
> Fix header filter popup when horizontal scrolling

- package.json
- src/lib/Utils/PropsUtils.test.ts
- src/lib/Utils/PropsUtils.ts
- src/lib/Utils/__snapshots__/PropsUtils.test.ts.snap
> Add getFilteredData to PropsUtils

- package.json
- src/Demos/DemosMenu.tsx
- src/lib/Components/TableUncontrolled/TableUncontrolled.test.tsx
- src/lib/Components/TableUncontrolled/TableUncontrolled.tsx
onDispatch should have state: ITableProps according to definitions
> remove childComponents from onDispatch call

- package.json
- src/lib/Components/CellEditorValidationMessage/CellEditorValidationMessage.test.tsx
- src/lib/Components/GroupedColumnsRow/GroupedColumnsRow.tsx
- src/lib/Components/HeadCell/HeadCell.tsx
- src/lib/Utils/GroupedColumnsUtils.ts
> Disable reordering for grouped column (as it is not supported)

- src/lib/Components/CellEditorBoolean/CellEditorBoolean.test.tsx
- src/lib/Components/CellEditorDate/CellEditorDate.test.tsx
- src/lib/Components/CellEditorNumber/CellEditorNumber.test.tsx
- src/lib/Components/CellEditorString/CellEditorString.test.tsx
- src/lib/Components/CellText/CellText.test.tsx
- src/lib/Components/DataRow/DataRow.test.tsx
- src/lib/Components/FilterRowBoolean/FilterRowBoolean.test.tsx
- src/lib/Components/FilterRowDate/FilterRowDate.test.tsx
- src/lib/Components/FilterRowNumber/FilterRowNumber.test.tsx
- src/lib/Components/FilterRowString/FilterRowString.test.tsx
- src/lib/Components/GroupRowContent/GroupRowContent.test.tsx
- src/lib/Components/HeadCellContent/HeadCellContent.test.tsx
- src/lib/Components/HeadCellResize/HeadCellResize.test.tsx
- src/lib/Components/PagingIndex/PagingIndex.test.tsx
- src/lib/Components/PagingPages/PagingPages.test.tsx
- src/lib/Components/PagingSize/PagingSize.test.tsx
- src/lib/Components/TableWrapper/TableWrapper.test.tsx
- src/lib/Utils/CellResizeUtils.test.ts
- src/lib/Utils/CellUtils.test.ts
- src/lib/Utils/PropsUtils.test.ts
worked on https://github.com/komarovalexander/ka-table/issues/407
> changed deprecated methods on jest.fn() mock function

- package.json
- src/lib/static/themes/default.scss
> fix $ka-filter-row-cell-padding customization

- package.json
- src/Demos/FilterRowCustomEditorDemo/FilterRowCustomEditorDemo.tsx
- src/lib/Utils/FilterUtils.ts
- src/lib/enums.ts
add ability to set not equal filter row operator for the column:
`filterRowOperator: '!='`
> Add IsNotEqual filter operator to the Filter Row

- package.json
- src/Demos/FilterRowDemo/FilterRowDemo.tsx
- src/lib/Components/FilterRowDate/FilterRowDate.test.tsx
- src/lib/Components/FilterRowDate/FilterRowDate.tsx
- src/lib/Utils/FilterUtils.test.ts
> Fix FilterRowDate timezone issue

- package.json
- src/lib/Components/TableUncontrolled/utils.ts
> Add columns to controlledPropsKeys
